name: release-please
on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: write
  pull-requests: write
  actions: read
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Debug: Show what outputs we got
      - name: Debug Release Please outputs
        run: |
          echo "Release created: ${{ steps.release.outputs.release_created }}"
          echo "Tag name: ${{ steps.release.outputs.tag_name }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"

  # Trigger PyPI publication when a release is created
  call-publish-workflow:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/publish-pypi.yml
    secrets: inherit